CREATE TABLE DEPARTMENT(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)
);

CREATE TABLE TITLE(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    `DESC` TEXT NOT NULL,
    STIPEND DOUBLE NOT NULL,
    CONSTRAINT PK_TITLE PRIMARY KEY (ID)
);

CREATE TABLE EMPLOYEE(
	ID INT,
	NAME VARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	ADDRESS TEXT,
	PHONE VARCHAR(20),
	GENDER BIT,
	EMAIL  VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	DEPARTMENT_ID INT NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES department(ID)
);

CREATE TABLE EMPLOYEE_TITLE(
	EMPLOYEE_ID INT NOT NULL,
	TITLE_ID INT NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (EMPLOYEE_ID,TITLE_ID),
    CONSTRAINT FK_EMPLOYEE_TIILE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_EMPLOYEE_TITLE_TILLE FOREIGN KEY (TITLE_ID) REFERENCES title(ID)
);