-- patchset3 --> CUSTOMER
CREATE TABLE CUSTOMER(
	ID INT,
	NAME VARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	ADDRESS TEXT,
	PHONE VARCHAR(20),
	GENDER BIT NOT NULL,
	EMAIL  VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
    );