-- patchset4 --> PAYMENT_METHOD, ORDER, ORDER_DETAIL, BILL
CREATE TABLE PAYMENT_METHOD(
	ID INT,
	`DESC` VARCHAR(100) NOT NULL,
    CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (ID)
);
CREATE TABLE `ORDER`(
	ID INT,
	DELIVERY_ADDRESS TEXT NOT NULL,
	TOTAL_FEE DOUBLE NOT NULL,
	DELIVERY_DATE DATE,
	DELIVERY_FEE DOUBLE,
	CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    CUSTOMER_ID INT NOT NULL,
    PAYMENT_METHOD_ID INT NOT NULL,
    CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_CUSTOMER FOREIGN KEY (CUSTOMER_ID) REFERENCES customer(ID),
    CONSTRAINT FK_ORDER_PAYMENT_METHOD FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID)
);
CREATE TABLE ORDER_DETAIL(
	ORDER_ID INT NOT NULL,
	ITEM_ID INT NOT NULL,
    AMOUNT INT NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ORDER_ID,ITEM_ID),
    CONSTRAINT FK_ORDER_DETAIL_ORDERE FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_ITEM FOREIGN KEY (ITEM_ID) REFERENCES item(ID)
);
CREATE TABLE BILL(
	ID INT,
	`CREATED_AT` DATETIME DEFAULT CURRENT_TIMESTAMP(),
    ORDER_ID INT NOT NULL,
    CONSTRAINT PK_BILL PRIMARY KEY (ID),
    CONSTRAINT FK_BILL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `order`(ID)
);
ALTER TABLE BILL
ADD CONSTRAINT UNIQUE_ORDER_ID UNIQUE (ORDER_ID);

