-- 1.tạo database
CREATE SCHEMA JAVA18_SHOPPING CHARSET utf8mb4;

USE JAVA18_SHOPPING;


-- 2.chọn thứ tự các bảng cần thực hiện

-- patchset1 -->item
-- provider,size,Item_group,ITEM,ITEM DETAIL
CREATE TABLE `PROVIDER`
(
	ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    TAX_CODE VARCHAR(20) NOT NULL,
    ADDRESS TEXT		NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_PROVIDER PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS `SIZE`;
CREATE TABLE  `SIZE`
(
	ID VARCHAR(10),
    GENDER  TINYINT NOT NULL,
	`DESC` TEXT,
    CONSTRAINT PK_SIZEZ PRIMARY KEY (ID),
    CONSTRAINT CHK_SIZE_ID CHECK (ID IN ('S','M','L','XL','XXL','XXXL')),
    CONSTRAINT CHK_GENDER CHECK (ID IN (0,1))
);
CREATE TABLE `ITEM_GROUP`
(
	ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    CONSTRAINT PK_ITEM_GROUP PRIMARY KEY(ID)
);
CREATE TABLE `ITEM`
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    COLOR VARCHAR(20) NOT NULL,
    MATERIAL VARCHAR(100) NOT NULL,
    IMAGE_01 TEXT NOT NULL,
    IMAGE_02 TEXT NOT NULL,
    LAST_UPDATE_AT DATE NOT NULL,
    ITEM_GROUP_ID INT NOT NULL,
    PROVIDER_ID INT NOT NULL,
    CONSTRAINT PK_ITEM PRIMARY KEY(ID),
    CONSTRAINT FK_ITEM_GROUP_ID FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP(ID),
    CONSTRAINT FK_PROVIDER_ID FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER(ID)
);
CREATE TABLE ITEM_DETAIL
(
	ITEM_ID INT,
    SIZE_ID VARCHAR(10),
    AMOUNT INT NOT NULL,
    SELL_PRICE FLOAT NOT NULL,
    BUY_PRICE FLOAT NOT NULL,
	CONSTRAINT PK_ITEM_DETAIL PRIMARY KEY(ITEM_ID,SIZE_ID),
    CONSTRAINT FK_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
    CONSTRAINT FK_SIZE_ID FOREIGN KEY (SIZE_ID) REFERENCES SIZE(ID)
);

-- patchset2 -->employee
-- DEPATYMENT,TITLE,EMPLOYEE,EMPLOYEE_DETAIL
CREATE TABLE `DEPATYMENT`
(
	ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DEPATYMENT PRIMARY KEY (ID)
);
CREATE TABLE `TITLE`
(
	ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    `DESC` TEXT,
    CONSTRAINT PK_TITLE PRIMARY KEY (ID)
);
CREATE TABLE `EMPLOYEE`
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ADDRESS TEXT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    GENDER  TINYINT NOT NULL,
	EMAIL TEXT NOT NULL,
    `PASSWORD` TEXT NOT NULL,
    DEPATYMENT_ID INT NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID),
    CONSTRAINT FK_DEPATYMENT_ID FOREIGN KEY (DEPATYMENT_ID) REFERENCES DEPATYMENT(ID),
    CONSTRAINT CHK_GENDER CHECK (ID IN (0,1)),
	CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE  '%@gmail.com')
);
CREATE TABLE `EMPLOYEE_DETAIL`
(
	EMPLOYEE_ID INT,
    TITLE_ID INT ,
	CONSTRAINT PK_EMPLOYEE_DETAIL PRIMARY KEY(EMPLOYEE_ID,TITLE_ID),
    CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_TITLE_ID FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
);
-- patchset3 -->CUSTOMER
CREATE TABLE `CUSTOMER`
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    DATE_OF_BIRTH DATE NOT NULL,
    ADDRESS TEXT NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    GENDER  TINYINT NOT NULL,
	EMAIL TEXT NOT NULL,
    `PASSWORD` TEXT NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY(ID),
    CONSTRAINT CHK_GENDER CHECK (ID IN (0,1)),
	CONSTRAINT CHK_EMAIL CHECK (EMAIL LIKE  '%@gmail.com')
);

-- patchset4 -->order
-- PAYMENT_METHOD,ORDER,ORDER_DETAIL,BILL
CREATE TABLE `PAYMENT_METHOD`
(
	ID INT ,
    `DESC` TEXT,
    CONSTRAINT PK_PAYMENT_METHOD PRIMARY KEY (ID)
);
CREATE TABLE `ORDER`
(
	ID INT,
    CUSTOMER_ID INT NOT NULL,
    DELIVERY_ADDRESS TEXT NOT NULL,
    PAYMENT_METHOD_ID INT NOT NULL,
    TOTAL_FEE FLOAT NOT NULL,
    DELIVERY_DATE  DATE NOT NULL,
	DELIVERY_FEE FLOAT NOT NULL,
    CREATE_AT DATE NOT NULL,
    CONSTRAINT PK_ORDER PRIMARY KEY(ID),
	CONSTRAINT FK_CUSTOMER_ID FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID),
	CONSTRAINT FK_PAYMENT_METHOD_ID FOREIGN KEY (PAYMENT_METHOD_ID) REFERENCES PAYMENT_METHOD(ID)
);
CREATE TABLE `ORDER_DETAIL`
(
	ORDER_ID INT ,
    ITEM_ID INT ,
    AMOUNT INT NOT NULL,
    CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY (ORDER_ID,ITEM_ID),
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ITEM_ID FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID)
);
CREATE TABLE `BILL`
(
	ID INT ,
    ORDER_ID INT NOT NULL,
    CREATE_AT DATE NOT NULL,
    CONSTRAINT PK_BILL PRIMARY KEY (ID),
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID)
);

-- patchset5 -->DELIVERY-STATUS,ORDER_DELIVERY_STATUS_DETAIL
CREATE TABLE `DELIVERY_STATUS`
(
	ID INT ,
    `DESC` TEXT,
    CONSTRAINT PK_DELIVERY_STATUS PRIMARY KEY (ID)
);
CREATE TABLE `ORDER_DELIVERY_STATUS_DETAIL`
(
	ORDER_ID INT ,
	STATUS_ID INT ,
    EMPLOYEE_ID INT NOT NULL,
    LAST_UPDATE_AT DATE NOT NULL,
    CONSTRAINT PK_ORDER_DELIVERY_STATUS_DETAIL PRIMARY KEY (ORDER_ID,STATUS_ID),
    CONSTRAINT FK_ORDER_ID FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_STATUS_ID FOREIGN KEY (STATUS_ID) REFERENCES DELIVERY_STATUS(ID),
	CONSTRAINT FK_EMPLOYEE_ID FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);




