-- 1. Tạo database
CREATE SCHEMA JAVA18_SHOPPING CHAR SET utf8mb4;
USE JAVA18_SHOPPING;

-- 2. Chọn thứ tự các bảng cần thực hiện

-- patchset1 --> PROVIDER, SIZE, ITEM_GROUP, ITEM, ITEM_DETAIL

-- create table provider
CREATE TABLE `PROVIDER`
(
	ID         INT,
    `NAME`     VARCHAR(100) NOT NULL,
    TAX_CODE   VARCHAR(20)  NOT NULL,
    ADDRESS    TEXT         NOT NULL,
    PHONE      VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_PROVIDER PRIMARY KEY (ID)
);

-- create table size
DROP TABLE IF EXISTS `SIZE`;
CREATE TABLE `SIZE`
(
	ID     VARCHAR(10),
    GENDER TINYINT NOT NULL,
    `DESC` TEXT,
    CONSTRAINT PK_SIZE PRIMARY KEY (ID),
    CONSTRAINT CHK_SIZE_ID CHECK (ID IN ('S', 'M', 'L', 'XL', 'XXL', 'XXXL')),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN (0, 1))
);

-- patchset2 --> DEPARTMENT, TITLE, EMPLOYEE, EMPLOYEE_DETAIL

-- patchset3 --> CUSTOMER

-- patchset4 --> PAYMENT_METHOD, ORDER, ORDER_DETAIL, BILL

-- patchset5 --> DELIVERY_STATUS, ORDER_DELIVERY_STATUS_DETAIL