CREATE SCHEMA LESSON17_DACTAI CHAR SET utf8mb4;
USE LESSON17_DACTAI;


DROP TABLE IF EXISTS `CLASS`;
CREATE TABLE `CLASS`
(
	ID 			INT				PRIMARY KEY,
	NAME 		VARCHAR(100) 	NOT NULL,
    TEACHER 	VARCHAR(100) 	NOT NULL
);

DROP TABLE IF EXISTS `STUDENT`;
CREATE TABLE `STUDENT`
(
	ID 			INT				PRIMARY KEY,
	NAME 		VARCHAR(100) 	NOT NULL,
    GENDER 		VARCHAR(20) 	NOT NULL,
    CLASS_ID 	INT 			NOT NULL
    
);
ALTER TABLE `STUDENT` 
ADD CONSTRAINT FK_STUDENT_CLASS	FOREIGN KEY (CLASS_ID) 	REFERENCES CLASS(ID);

DROP TABLE IF EXISTS `RESULT`;
CREATE TABLE `RESULT`
(
	STUDENT_ID 	INT	,
	`SUBJECT` 	VARCHAR(100) 	NOT NULL,
    SCORE 		DOUBLE 			NOT NULL,
	CONSTRAINT PK_RESULT 		PRIMARY KEY (STUDENT_ID, SUBJECT),
    CONSTRAINT CHK_SUBJECT 	CHECK (`SUBJECT` IN ('Math', 'Literature', 'History'))
);

ALTER TABLE `RESULT` 
ADD CONSTRAINT FK_RESULT_STUDENT	FOREIGN KEY (STUDENT_ID) 	REFERENCES STUDENT(ID);

