-- 1.tạo database
CREATE SCHEMA JAVA18_SHOPPING CHARSET utf8mb4;

USE JAVA18_SHOPPING;


-- 2.chọn thứ tự các bảng cần thực hiện

-- patchset1 -->item
-- provider,size,Item_group,ITEM,ITEM DETAIL
CREATE TABLE `PROVIDER`
(
	ID INT ,
    `NAME` VARCHAR(100) NOT NULL,
    TAX_CODE VARCHAR(20) NOT NULL,
    ADDRESS TEXT		NOT NULL,
    PHONE VARCHAR(20) NOT NULL,
    CONSTRAINT PK_PROVIDER PRIMARY KEY (ID)
);
DROP TABLE IF EXISTS `SIZE`;
CREATE TABLE  `SIZE`
(
	ID VARCHAR(10),
    GENDER  TINYINT NOT NULL,
	`DESC` TEXT,
    CONSTRAINT PK_SIZEZ PRIMARY KEY (ID),
    CONSTRAINT CHK_SIZE_ID CHECK (ID IN ('S','M','L','XL','XXL','XXXL')),
    CONSTRAINT CHK_GENDER CHECK (ID IN (0,1))
);
-- CREATE TABLE `ITEM_GROUP`
CREATE TABLE `ITEM_GROUP`
(
	ID INT ,
    `NAME` VARCHAR(100) NOT NULL
);
ALTER TABLE `ITEM_GROUP`
ADD CONSTRAINT PK_ITEM_GROUP PRIMARY KEY(ID);

-- CREATE TABLE `ITEM`
CREATE TABLE `ITEM`
(
ID INT,
    `NAME` VARCHAR(100) NOT NULL,
    COLOR VARCHAR(20) ,
    MATERIAL VARCHAR(100),
    IMAGE_01 VARCHAR(100) ,
    IMAGE_02 VARCHAR(100) ,
    LAST_UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    ITEM_GROUP_ID INT ,
    PROVIDER_ID INT 
);
ALTER TABLE `ITEM`
ADD CONSTRAINT PK_ITEM PRIMARY KEY(ID);
ALTER TABLE `ITEM`
ADD  CONSTRAINT FK_ITEM_ITEM_GROUP FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP(ID);
ALTER TABLE `ITEM`
ADD CONSTRAINT FK_ITEM_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER(ID);
ALTER TABLE `ITEM`
CHANGE ITEM_GROUP_ID ITEM_GROUP_ID INT NOT NULL;
ALTER TABLE `ITEM`
CHANGE PROVIDER_ID PROVIDER_ID INT NOT NULL;

CREATE TABLE `ITEM_DETAIL`
(
	ITEM_ID INT,
    SIZE_ID VARCHAR(10),
    AMOUNT INT NOT NULL,
    BUY_PRICE DOUBLE NOT NULL,
    SELL_PRICE DOUBLE NOT NULL,
	CONSTRAINT PK_ITEM_DETAIL PRIMARY KEY(ITEM_ID,SIZE_ID),
    CONSTRAINT FK_ITEM_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
    CONSTRAINT FK_ITEM_SIZE FOREIGN KEY (SIZE_ID) REFERENCES SIZE(ID)
);
