CREATE TABLE `DELIVERY_STATUS`
(
	ID INT ,
    `DESC` VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DELIVERY_STATUS PRIMARY KEY (ID)
);
CREATE TABLE `ORDER_DELIVERY_STATUS_DETAIL`
(
	ORDER_ID INT ,
	STATUS_ID INT ,
    EMPLOYEE_ID INT NOT NULL,
    LAST_UPDATE_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_ORDER_DELIVERY_STATUS_DETAIL PRIMARY KEY (ORDER_ID,STATUS_ID),
    CONSTRAINT FK_ODSD_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ODSD_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DELIVERY_STATUS(ID),
	CONSTRAINT FK_ODSD_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);