-- patchset1 --> PROVIDER, SIZE, ITEM_GROUP, ITEM, ITEM_DETAIL

-- create table provider
CREATE TABLE `PROVIDER`
(
	ID         INT,
    `NAME`     VARCHAR(100) NOT NULL,
    TAX_CODE   VARCHAR(20)  NOT NULL,
    ADDRESS    TEXT         NOT NULL,
    PHONE      VARCHAR(20)  NOT NULL,
    CONSTRAINT PK_PROVIDER PRIMARY KEY (ID)
);

-- create table size
DROP TABLE IF EXISTS `SIZE`;
CREATE TABLE `SIZE`
(
	ID     VARCHAR(10),
    GENDER TINYINT NOT NULL,
    `DESC` TEXT,
    CONSTRAINT PK_SIZE PRIMARY KEY (ID),
    CONSTRAINT CHK_SIZE_ID CHECK (ID IN ('S', 'M', 'L', 'XL', 'XXL', 'XXXL')),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN (0, 1))
);

-- create table item_group
CREATE TABLE `ITEM_GROUP`
(
	ID INT,
    `NAME` VARCHAR(100) NOT NULL
);
-- add pk, fk
ALTER TABLE `ITEM_GROUP`
ADD CONSTRAINT PK_ITEM_GROUP PRIMARY KEY (ID);

-- create table item
CREATE TABLE ITEM 
(
	ID INT,
    `NAME`          VARCHAR(100) NOT NULL,
    COLOR           VARCHAR(20),
    MATERIAL        VARCHAR(100),
    IMAGE_01        VARCHAR(100),
    IMAGE_02        VARCHAR(100),
    LAST_UPDATED_AT DATETIME DEFAULT current_timestamp(),
    ITEM_GROUP_ID   INT,
    PROVIDER_ID     INT
);

-- add pk, fk
ALTER TABLE `ITEM`
ADD CONSTRAINT PK_ITEM PRIMARY KEY (ID);

ALTER TABLE `ITEM`
ADD CONSTRAINT FK_ITEM_ITEM_GROUP FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP(ID);

ALTER TABLE `ITEM`
ADD CONSTRAINT FK_ITEM_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER(ID);

ALTER TABLE `ITEM`
CHANGE ITEM_GROUP_ID ITEM_GROUP_ID INT NOT NULL;

ALTER TABLE `ITEM`
CHANGE PROVIDER_ID PROVIDER_ID INT NOT NULL;

-- create table item_detail
CREATE TABLE ITEM_DETAIL
(
	ITEM_ID    INT,
    SIZE_ID    VARCHAR(10),
    AMOUNT     INT    NOT NULL,
    BUY_PRICE  DOUBLE NOT NULL,
    SELL_PRICE DOUBLE NOT NULL,
    CONSTRAINT PK_ITEM_DETAIL      PRIMARY KEY (ITEM_ID, SIZE_ID),
    CONSTRAINT FK_ITEM_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
	CONSTRAINT FK_ITEM_SIZE        FOREIGN KEY (SIZE_ID) REFERENCES SIZE(ID)
);
