-- create table provider
DROP TABLE IF EXISTS `PROVIDER`;
CREATE TABLE `PROVIDER`
(
	ID 				INT,
	`NAME` 			VARCHAR(100) 	NOT NULL,
    TAX_CODE 		VARCHAR(20) 	NOT NULL,
    ADDRESS 		TEXT 			NOT NULL,
    PHONE 			VARCHAR(20) 	NOT NULL,
    CONSTRAINT PK_PROVIDER PRIMARY KEY (ID)
);

-- create table size
DROP TABLE IF EXISTS `SIZE`;
CREATE TABLE `SIZE`
(
	ID 				VARCHAR(10),
    GENDER 			TINYINT 		NOT NULL, 
    `DESC` 			TEXT,
    CONSTRAINT PK_SIZE PRIMARY KEY (ID),
    CONSTRAINT CHK_SIZE_ID CHECK (ID IN ('S', 'M', 'L', 'XL', 'XXL', 'XXXL')),
    CONSTRAINT CHK_GENDER CHECK (GENDER IN (0, 1))
);

-- create table item_group
DROP TABLE IF EXISTS `ITEM_GROUP`;
CREATE TABLE `ITEM_GROUP`
(
	ID 				INT,
    `NAME` 			VARCHAR(100) 	NOT NULL,
    CONSTRAINT PK_ITEM_GROUP PRIMARY KEY (ID)
);

-- create table item
DROP TABLE IF EXISTS `ITEM`;
CREATE TABLE `ITEM`
(
	ID 				INT,
    `NAME` 			VARCHAR(100) 	NOT NULL,
    COLOR 			VARCHAR(100),
    MATERIAL 		VARCHAR(100),
    IMAGE_01 		VARCHAR(100),
    IMAGE_02 		VARCHAR(100),
    LAST_UPDATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP(),
    ITEM_GROUP_ID 	INT,
    PROVIDER_ID 	INT,
    CONSTRAINT PK_ITEM PRIMARY KEY (ID),
    CONSTRAINT FK_ITEM_ITEM_GROUP FOREIGN KEY (ITEM_GROUP_ID) REFERENCES ITEM_GROUP(ID),
    CONSTRAINT FK_ITEM_PROVIDER FOREIGN KEY (PROVIDER_ID) REFERENCES PROVIDER(ID)
);

ALTER TABLE `ITEM`
CHANGE ITEM_GROUP_ID ITEM_GROUP_ID INT NOT NULL;

ALTER TABLE `ITEM`
CHANGE PROVIDER_ID PROVIDER_ID INT NOT NULL;

-- create table item_detail
DROP TABLE IF EXISTS `ITEM_DETAIL`;
CREATE TABLE `ITEM_DETAIL`
(
    AMOUNT 			INT 			NOT NULL,
    SELL_PRICE 		DOUBLE 			NOT NULL,
    BUY_PRICE 		DOUBLE 			NOT NULL,
    ITEM_ID 		INT,
    SIZE_ID 		VARCHAR(10),
    CONSTRAINT PK_ITEM_DETAIL PRIMARY KEY (ITEM_ID, SIZE_ID),
    CONSTRAINT FK_ITEM_DETAIL_ITEM FOREIGN KEY (ITEM_ID) REFERENCES ITEM(ID),
    CONSTRAINT FK_ITEM_DETAIL_SIZE FOREIGN KEY (SIZE_ID) REFERENCES SIZE(ID)
);
