-- patchset2 --> DEPARTMENT, TITLE, EMPLOYEE, EMPLOYEE_DETAIL

-- create table department
DROP TABLE `java18_shopping_test2`.`department`;
CREATE TABLE DEPARTMENT
(
	ID INT,
    `NAME` VARCHAR(100),
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY(ID)
);

-- create table title
CREATE TABLE TITLE
(
	ID INT,
    `NAME` VARCHAR(100),
    `DESC` TEXT NOT NULL,
    STRIPEND DOUBLE NOT NULL,
    CONSTRAINT PK_TITLE PRIMARY KEY(ID)
);

-- create table employee
CREATE TABLE EMPLOYEE
(
	ID INT,
	`NAME` VARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE NOT NULL,
	ADDRESS TEXT,
	PHONE VARCHAR(20),
	GENDER BIT, -- EXPECT 0 1
	EMAIL VARCHAR(100) NOT NULL,
	`PASSWORD` VARCHAR(100) NOT NULL,
	DEPARTMENT_ID INT NOT NULL,
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY(ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- create table employee_title
CREATE TABLE EMPLOYEE_TITLE
(
	EMPLOYEE_ID INT,
    TITLE_ID INT,
    CONSTRAINT PK_EMPLOYEE_TITLE PRIMARY KEY (EMPLOYEE_ID, TITLE_ID),
    CONSTRAINT FK_EMPLOYEE_TITLE_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_EMPLOYEE_TITLE_TITLE FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
);