-- create table department
DROP TABLE IF EXISTS `DEPARTMENT`;
CREATE TABLE `DEPARTMENT`
(
	ID 			INT,
    `NAME` 		VARCHAR(100) NOT NULL,
    CONSTRAINT PK_DEPARTMENT PRIMARY KEY (ID)
);

-- create table title
DROP TABLE IF EXISTS `TITLE`;
CREATE TABLE `TITLE`
(
	ID 			INT,
    `NAME` 		VARCHAR(100) 	NOT NULL,
    `DESC`	 	TEXT 			NOT NULL,
    STPEND 		DOUBLE 			NOT NULL,
    CONSTRAINT PK_TITLE PRIMARY KEY (ID)
);

-- create table employee
DROP TABLE IF EXISTS `EMPLOYEE`;
CREATE TABLE `EMPLOYEE`
(
	ID 				INT,
    `NAME` 			VARCHAR(100) 	NOT NULL,
    DATE_OF_BIRTH 	DATE 			NOT NULL,
    ADDRESS 		TEXT,
    PHONE 			VARCHAR(20),
    GENDER 			BIT 			NOT NULL,
    EMAIL 			VARCHAR(100) 	NOT NULL,
    `PASSWORD` 		VARCHAR(100) 	NOT NULL,
    DEPARTMENT_ID 	INT 			NOT NULL,
    -- CONSTRAINT CHK_EMPLOYEE_GENDER CHECK (GENDER IN (0, 1)),
    CONSTRAINT PK_EMPLOYEE PRIMARY KEY (ID),
    CONSTRAINT FK_EMPLOYEE_DEPARTMENT FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENT(ID)
);

-- create table employee_title
DROP TABLE IF EXISTS `EMPLOYEE_TITLE`;
CREATE TABLE `EMPLOYEE_TITLE`
(
	EMPLOYEE_ID 	INT,
    TITLE_ID 		INT,
    CONSTRAINT PK_EMPLOYEE_TITLE PRIMARY KEY (EMPLOYEE_ID, TITLE_ID),
    CONSTRAINT FK_EMPLOYEE_DETAIL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID),
    CONSTRAINT FK_EMPLOYEE_DETAIL_TITLE FOREIGN KEY (TITLE_ID) REFERENCES TITLE(ID)
);