-- create table customer
DROP TABLE IF EXISTS `CUSTOMER`;
CREATE TABLE `CUSTOMER`
(
	ID 				INT,
    `NAME` 			VARCHAR(100) 	NOT NULL,
    DATE_OF_BIRTH 	DATE 			NOT NULL,
    ADDRESS 		TEXT,
    PHONE 			VARCHAR(20),
    GENDER 			BIT,
    EMAIL 			VARCHAR(100) 	NOT NULL,
    `PASSWORD` 		VARCHAR(100) 	NOT NULL,
    -- CONSTRAINT CHK_CUSTOMER_GENDER CHECK (GENDER IN (0, 1)),
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);