
CREATE TABLE CUSTOMER
(
	ID INT,
	`NAME` VARCHAR(100) NOT NULL,
	DATE_OF_BIRTH DATE,
	ADDRESS TEXT,
	PHONE VARCHAR(10),
	GENDER BIT,
	EMAIL VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
    CONSTRAINT PK_CUSTOMER PRIMARY KEY (ID)
);