-- patchset5 --> DELIVERY_STATUS, ORDER_DELIVERY_STATUS_DETAIL

-- create table delivery status
CREATE TABLE DELIVERY_STATUS
(
	ID INT,
    DES TEXT NOT NULL,
    CONSTRAINT PK_DELIVERY_STATUS PRIMARY KEY (ID)
);

CREATE TABLE ORDER_DELIVERY_STATUS_DETAIL
(
	ORDER_ID INT,
    STATUS_ID INT,
    EMPLOYEE_ID INT,
    LAST_UPDATE_AT DATETIME,
    CONSTRAINT PK_ORDER_DELIVERY_STATUS_DETAIL PRIMARY KEY (ORDER_ID, STATUS_ID),
    CONSTRAINT FK_DSD_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_DSD_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DELIVERY_STATUS (ID)
);