-- create delivery_status
DROP TABLE IF EXISTS `DELIVERY_STATUS`;
CREATE TABLE `DELIVERY_STATUS`
(
	ID 				INT,
    `DESC` 			VARCHAR(100)	NOT NULL,
    CONSTRAINT PK_DELIVERY_STATUS PRIMARY KEY (ID)
);

-- create order_delivery_status_detail
DROP TABLE IF EXISTS `ORDER_DELIVERY_STATUS_DETAIL`;
CREATE TABLE `ORDER_DELIVERY_STATUS_DETAIL`
(
	LAST_UPDATED_AT 	DATETIME DEFAULT CURRENT_TIMESTAMP(),
    ORDER_ID 			INT,
    STATUS_ID 			INT,
    EMPLOYEE_ID 		INT 	NOT NULL,
    CONSTRAINT PK_ORDER_DELIVERY_STATUS_DETAIL PRIMARY KEY (ORDER_ID, STATUS_ID),
    CONSTRAINT FK_ORDER_DELIVERY_STATUS_DETAIL_ORDER FOREIGN KEY (ORDER_ID) REFERENCES `ORDER`(ID),
    CONSTRAINT FK_ORDER_DELIVERY_STATUS_DETAIL_DELIVERY_STATUS FOREIGN KEY (STATUS_ID) REFERENCES DELIVERY_STATUS(ID),
    CONSTRAINT FK_ORDER_DELIVERY_STATUS_DETAIL_EMPLOYEE FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEE(ID)
);
