USE JAVA18_SHOPPING;
-- DISABLE ALLL FKS
SET FOREIGN_KEY_CHECK = 0;

 DELETE FROM `ITEM_DETAIL`;
 DELETE FROM `EMPLOYEE_TITLE`;
 DELETE FROM `ORDER_DETAIL`;
 DELETE FROM `ORDER_DELIVERY_STATUS_DETAIL`;
DELETE FROM `ITEM`;
DELETE FROM `EMPLOYEE`;
DELETE FROM `BILL`;
DELETE FROM `ORDER`;
 DELETE FROM `CUSTOMER`;

 
 DELETE FROM `SIZE`;
DELETE FROM`TITLE`;
 DELETE FROM `TITLE`;
  DELETE FROM `DEPARTMENT`;
DELETE FROM `PROVIDER`;
DELETE FROM `ITEM_GROUP`;
DELETE FROM `DELIVERY_STATUS`;
 
-- ENABLE  ALL FKS;
SET FOREIGN_KEY_CHECK = 1;


